### PR TITLE
add directory to File ResourceType

### PR DESCRIPTION
**Pull request by TharinduDG**
**CDF-13219** add `directory` attribute to `File` resource type

### CODE REVIEW

**Review by hakontro — APPROVED** [review]
LGTM :+1:

**Comment by hakontro** [comment]
@TharinduDG nvm the codecov going down a bit, it's np in this case

**Comment by exyi** [comment]
>@TharinduDG nvm the codecov going down a bit, it's np in this case

I think you could just add directory to some existing tests.

**Comment by TharinduDG** [comment]
> I think you could just add directory to some existing tests :P

Correct if I'm wrong, I couldn't find any tests that uses attributes of `FilesInsertSchema`, `FilesReadSchema`, or `FilesUpsertSchema`.
Therefore I didn't make any changes to the tests.

**Pull request merged**
