### PR TITLE
DOCS 80 - Fixed broken links

### PR DESCRIPTION
**Pull request by sowmya-rajan**

### CODE REVIEW

**Review by exyi — COMMENTED** [review]
Not sure if this is a great idea, the links are not broken in this repo. This just makes them unnecessarily absolute, which will break the links when the repository get's forked or renamed (to cdf-spark-datasource or cognite-spark-datasource, for example, as we should have done already...)

**Comment by sowmya-rajan** [comment]
> Not sure if this is a great idea, the links are not broken in this repo. This just makes them unnecessarily absolute, which will break the links when the repository get's forked or renamed (to cdf-spark-datasource or cognite-spark-datasource, for example, as we should have done already...)

Hey @exyi, Thank you for the comment. Currently, both the links are throwing up a 404 error. If you could let me know a possible link fix for it, I can go ahead and make them?

**Comment by exyi** [comment]
I don't know how the Cognite docs website works, but in this file the links are working as expected: https://github.com/cognitedata/cdp-spark-datasource#comprehensive-examples, only on the docs.cognite.com web it's broken. It seems that the documentation is essentially the same, and I don't know if it's somehow created automatically or someone copy pasted that without adjusting the links

**Comment by sowmya-rajan** [comment]
> I don't know how the Cognite docs website works, but in this file the links are working as expected: https://github.com/cognitedata/cdp-spark-datasource#comprehensive-examples, only on the docs.cognite.com web it's broken. It seems that the documentation is essentially the same, and I don't know if it's somehow created automatically or someone copy pasted that without adjusting the links

Hey @exyi, The link is working fine in this file. It was broken in `docs.cognite.com`. I have updated the link on the docs website by providing the full URLs. Do let me know if that works. If everything looks good, it would be great if you could give me a thumbs up for a go-ahead. :)

**Review by arnekv — APPROVED** [review]
lgtm :-)

**Pull request merged**
