### PR TITLE
Release 0.4.5

### PR DESCRIPTION
**Pull request by wjoel**

### CODE REVIEW

**Comment by Tapped** [comment]
Could we try to get the metric period fix in before the release?

**Comment by wjoel** [comment]
Sure, just rebase and merge.

**Comment by Tapped** [comment]
The Metrics fixes are in now 👍 

We should test out using Ganglia and Datadog with databricks or some other sink, the metrics should be visible there as well.

**Comment by wjoel** [comment]
@Tapped I still need an "Approve" to merge this.

**Comment by wjoel** [comment]
Unless you want to test out Ganglia metrics first: https://docs.databricks.com/user-guide/clusters/metrics.html

**Comment by Tapped** [comment]
Nah, I think it will work fine, and probably worked fine before as well, though had duplicate information in the metrics.

**Pull request merged**
