### PR TITLE
Fix leaking threads by creating many sttpBackends

### PR DESCRIPTION
**Pull request by exyi**
Hopefully...

### CODE REVIEW

**Review by hakontro — COMMENTED** [review]
Neat. What is the difference here?

**Review by emelvarol-cognite — COMMENTED** [review]
Reminder: bump the version

**Comment by exyi** [comment]
> Neat. What is the difference here?

This way we use the single sttpBackend from CdpConnector, don't create new one for each request. Creating sttpBackend also creates a threadpool which contains some threads and thus leaks them

**Review by hakontro — APPROVED** [review]
LGTM

**Pull request merged**
