### PR TITLE
Release version 1.2.16

### PR DESCRIPTION
**Pull request by hakontro**

### CODE REVIEW

**Comment by wjoel** [comment]
I just merged https://github.com/cognitedata/cdp-spark-datasource/pull/404, let's include that one as well. Will see if I can fix #405 as well, but we don't have to wait for it.

**Comment by hakontro** [comment]
> I just merged #404, let's include that one as well. Will see if I can fix #405 as well, but we don't have to wait for it.

I asked @sush03 to rebase it just now, should probably coordinate with her so we don't do double work.

**Comment by wjoel** [comment]
@hakontro / @sush03 I have a rebase done locally but some tests are failing due errors in that PR.

**Comment by wjoel** [comment]
Let's do a release without #404, and do another (small) release once that's ready to go.

**Pull request merged**
